Update open source community files
alliander-opensource/power-grid-model-benchmark pull request #1
Opened 2022-01-26 12:19 UTC by Jonasvdbo

Updated the readme.md and added the following open source community files:

- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- PROJECT_GOVERNANCE.md
- SUPPORT.md

Signed-off-by: Jonas van den Bogaard 3628277+Jonasvdbo@users.noreply.github.com

2022-01-26 12:19 UTC, Jonasvdbo commented
@TonyXiang8787 Can you review this PR?

2022-01-26 13:55 UTC, TonyXiang8787 requested changes
also add requirements file

2022-01-26 16:39 UTC, Jonasvdbo commented on README.md
> +`pip install -r requirements.txt`
Not fully understand what you mean @TonyXiang8787. My understanding is that there is a requirements file: https://github.com/Jonasvdbo/power-grid-model-benchmark/blob/Update-open-source-community-files/requirements.txt

2022-01-26 19:10 UTC, TonyXiang8787 commented on README.md
> +`pip install -r requirements.txt`
You are correct. Please add license header also to `requirements.txt`.

Moreover, you can just uncomment `power-grid-model` there without any index url. It is now an public PyPI package.

2022-01-27 07:55 UTC, TonyXiang8787 approved these changes

2022-01-27 07:55 UTC, merged

2022-01-27 07:56 UTC, Jonasvdbo commented on README.md
> +`pip install -r requirements.txt`
Good remarks. I will update the `requirements.txt`.